# Generated by Django 3.0.3 on 2020-03-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100, verbose_name="Author's name")),
                ('authorDetail', models.TextField(max_length=1000, verbose_name='Author description')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100, verbose_name='Book name')),
                ('bookYear', models.DateField(blank=True, null=True, verbose_name='Book release year')),
                ('bookDetail', models.TextField(max_length=500, verbose_name='Book description')),
                ('borrowedBy', models.CharField(blank=True, max_length=100, verbose_name='Borrowed by')),
                ('borrowedDate', models.DateField(blank=True, null=True, verbose_name='Borrowed on')),
                ('returnDate', models.DateField(blank=True, null=True, verbose_name='Will be returned on')),
                ('bookWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.Author', verbose_name="Author's name")),
            ],
        ),
    ]
